version: '3'

# OBS: I'M Using pm2 to manage services and etc... I'll put in docker 
services:
  server:
    container_name: ARMARINHO_SERVER
    build: '.'
    volumes:
      - ./:/node-app
      - ./node_modules:/node-app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    links:
      - db
    ports:
      - '9000:9000'

  db:
    image: 'mongo'
    container_name: ARMARINHO_MONGODB
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db

volumes:
  node_modules:
